// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Slaughterhouse.proto

package via.sdj3.slaughterhousegrpcspringboot.protobuf;

public interface AnimalRegNrOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AnimalRegNr)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 regNr = 1;</code>
   * @return The regNr.
   */
  int getRegNr();
}
