// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Slaughterhouse.proto

package via.sdj3.slaughterhousegrpcspringboot.protobuf;

/**
 * Protobuf type {@code AnimalPart}
 */
public final class AnimalPart extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AnimalPart)
    AnimalPartOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AnimalPart.newBuilder() to construct.
  private AnimalPart(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AnimalPart() {
    type_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AnimalPart();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AnimalPart(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            partWeight_ = input.readDouble();
            break;
          }
          case 16: {

            partNumber_ = input.readInt32();
            break;
          }
          case 26: {
            via.sdj3.slaughterhousegrpcspringboot.protobuf.Animal.Builder subBuilder = null;
            if (animalRef_ != null) {
              subBuilder = animalRef_.toBuilder();
            }
            animalRef_ = input.readMessage(via.sdj3.slaughterhousegrpcspringboot.protobuf.Animal.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(animalRef_);
              animalRef_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            type_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sdj3.slaughterhousegrpcspringboot.protobuf.SlaughterhouseOuterClass.internal_static_AnimalPart_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sdj3.slaughterhousegrpcspringboot.protobuf.SlaughterhouseOuterClass.internal_static_AnimalPart_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart.class, via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart.Builder.class);
  }

  public static final int PARTWEIGHT_FIELD_NUMBER = 1;
  private double partWeight_;
  /**
   * <code>double partWeight = 1;</code>
   * @return The partWeight.
   */
  @java.lang.Override
  public double getPartWeight() {
    return partWeight_;
  }

  public static final int PARTNUMBER_FIELD_NUMBER = 2;
  private int partNumber_;
  /**
   * <code>int32 partNumber = 2;</code>
   * @return The partNumber.
   */
  @java.lang.Override
  public int getPartNumber() {
    return partNumber_;
  }

  public static final int ANIMALREF_FIELD_NUMBER = 3;
  private via.sdj3.slaughterhousegrpcspringboot.protobuf.Animal animalRef_;
  /**
   * <code>.Animal animalRef = 3;</code>
   * @return Whether the animalRef field is set.
   */
  @java.lang.Override
  public boolean hasAnimalRef() {
    return animalRef_ != null;
  }
  /**
   * <code>.Animal animalRef = 3;</code>
   * @return The animalRef.
   */
  @java.lang.Override
  public via.sdj3.slaughterhousegrpcspringboot.protobuf.Animal getAnimalRef() {
    return animalRef_ == null ? via.sdj3.slaughterhousegrpcspringboot.protobuf.Animal.getDefaultInstance() : animalRef_;
  }
  /**
   * <code>.Animal animalRef = 3;</code>
   */
  @java.lang.Override
  public via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalOrBuilder getAnimalRefOrBuilder() {
    return getAnimalRef();
  }

  public static final int TYPE_FIELD_NUMBER = 4;
  private volatile java.lang.Object type_;
  /**
   * <code>string type = 4;</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>string type = 4;</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Double.doubleToRawLongBits(partWeight_) != 0) {
      output.writeDouble(1, partWeight_);
    }
    if (partNumber_ != 0) {
      output.writeInt32(2, partNumber_);
    }
    if (animalRef_ != null) {
      output.writeMessage(3, getAnimalRef());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, type_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Double.doubleToRawLongBits(partWeight_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, partWeight_);
    }
    if (partNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, partNumber_);
    }
    if (animalRef_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getAnimalRef());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, type_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart)) {
      return super.equals(obj);
    }
    via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart other = (via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart) obj;

    if (java.lang.Double.doubleToLongBits(getPartWeight())
        != java.lang.Double.doubleToLongBits(
            other.getPartWeight())) return false;
    if (getPartNumber()
        != other.getPartNumber()) return false;
    if (hasAnimalRef() != other.hasAnimalRef()) return false;
    if (hasAnimalRef()) {
      if (!getAnimalRef()
          .equals(other.getAnimalRef())) return false;
    }
    if (!getType()
        .equals(other.getType())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PARTWEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPartWeight()));
    hash = (37 * hash) + PARTNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getPartNumber();
    if (hasAnimalRef()) {
      hash = (37 * hash) + ANIMALREF_FIELD_NUMBER;
      hash = (53 * hash) + getAnimalRef().hashCode();
    }
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AnimalPart}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AnimalPart)
      via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPartOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sdj3.slaughterhousegrpcspringboot.protobuf.SlaughterhouseOuterClass.internal_static_AnimalPart_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sdj3.slaughterhousegrpcspringboot.protobuf.SlaughterhouseOuterClass.internal_static_AnimalPart_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart.class, via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart.Builder.class);
    }

    // Construct using via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      partWeight_ = 0D;

      partNumber_ = 0;

      if (animalRefBuilder_ == null) {
        animalRef_ = null;
      } else {
        animalRef_ = null;
        animalRefBuilder_ = null;
      }
      type_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sdj3.slaughterhousegrpcspringboot.protobuf.SlaughterhouseOuterClass.internal_static_AnimalPart_descriptor;
    }

    @java.lang.Override
    public via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart getDefaultInstanceForType() {
      return via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart.getDefaultInstance();
    }

    @java.lang.Override
    public via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart build() {
      via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart buildPartial() {
      via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart result = new via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart(this);
      result.partWeight_ = partWeight_;
      result.partNumber_ = partNumber_;
      if (animalRefBuilder_ == null) {
        result.animalRef_ = animalRef_;
      } else {
        result.animalRef_ = animalRefBuilder_.build();
      }
      result.type_ = type_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart) {
        return mergeFrom((via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart other) {
      if (other == via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart.getDefaultInstance()) return this;
      if (other.getPartWeight() != 0D) {
        setPartWeight(other.getPartWeight());
      }
      if (other.getPartNumber() != 0) {
        setPartNumber(other.getPartNumber());
      }
      if (other.hasAnimalRef()) {
        mergeAnimalRef(other.getAnimalRef());
      }
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double partWeight_ ;
    /**
     * <code>double partWeight = 1;</code>
     * @return The partWeight.
     */
    @java.lang.Override
    public double getPartWeight() {
      return partWeight_;
    }
    /**
     * <code>double partWeight = 1;</code>
     * @param value The partWeight to set.
     * @return This builder for chaining.
     */
    public Builder setPartWeight(double value) {
      
      partWeight_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double partWeight = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPartWeight() {
      
      partWeight_ = 0D;
      onChanged();
      return this;
    }

    private int partNumber_ ;
    /**
     * <code>int32 partNumber = 2;</code>
     * @return The partNumber.
     */
    @java.lang.Override
    public int getPartNumber() {
      return partNumber_;
    }
    /**
     * <code>int32 partNumber = 2;</code>
     * @param value The partNumber to set.
     * @return This builder for chaining.
     */
    public Builder setPartNumber(int value) {
      
      partNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 partNumber = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPartNumber() {
      
      partNumber_ = 0;
      onChanged();
      return this;
    }

    private via.sdj3.slaughterhousegrpcspringboot.protobuf.Animal animalRef_;
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sdj3.slaughterhousegrpcspringboot.protobuf.Animal, via.sdj3.slaughterhousegrpcspringboot.protobuf.Animal.Builder, via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalOrBuilder> animalRefBuilder_;
    /**
     * <code>.Animal animalRef = 3;</code>
     * @return Whether the animalRef field is set.
     */
    public boolean hasAnimalRef() {
      return animalRefBuilder_ != null || animalRef_ != null;
    }
    /**
     * <code>.Animal animalRef = 3;</code>
     * @return The animalRef.
     */
    public via.sdj3.slaughterhousegrpcspringboot.protobuf.Animal getAnimalRef() {
      if (animalRefBuilder_ == null) {
        return animalRef_ == null ? via.sdj3.slaughterhousegrpcspringboot.protobuf.Animal.getDefaultInstance() : animalRef_;
      } else {
        return animalRefBuilder_.getMessage();
      }
    }
    /**
     * <code>.Animal animalRef = 3;</code>
     */
    public Builder setAnimalRef(via.sdj3.slaughterhousegrpcspringboot.protobuf.Animal value) {
      if (animalRefBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        animalRef_ = value;
        onChanged();
      } else {
        animalRefBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Animal animalRef = 3;</code>
     */
    public Builder setAnimalRef(
        via.sdj3.slaughterhousegrpcspringboot.protobuf.Animal.Builder builderForValue) {
      if (animalRefBuilder_ == null) {
        animalRef_ = builderForValue.build();
        onChanged();
      } else {
        animalRefBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Animal animalRef = 3;</code>
     */
    public Builder mergeAnimalRef(via.sdj3.slaughterhousegrpcspringboot.protobuf.Animal value) {
      if (animalRefBuilder_ == null) {
        if (animalRef_ != null) {
          animalRef_ =
            via.sdj3.slaughterhousegrpcspringboot.protobuf.Animal.newBuilder(animalRef_).mergeFrom(value).buildPartial();
        } else {
          animalRef_ = value;
        }
        onChanged();
      } else {
        animalRefBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Animal animalRef = 3;</code>
     */
    public Builder clearAnimalRef() {
      if (animalRefBuilder_ == null) {
        animalRef_ = null;
        onChanged();
      } else {
        animalRef_ = null;
        animalRefBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Animal animalRef = 3;</code>
     */
    public via.sdj3.slaughterhousegrpcspringboot.protobuf.Animal.Builder getAnimalRefBuilder() {
      
      onChanged();
      return getAnimalRefFieldBuilder().getBuilder();
    }
    /**
     * <code>.Animal animalRef = 3;</code>
     */
    public via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalOrBuilder getAnimalRefOrBuilder() {
      if (animalRefBuilder_ != null) {
        return animalRefBuilder_.getMessageOrBuilder();
      } else {
        return animalRef_ == null ?
            via.sdj3.slaughterhousegrpcspringboot.protobuf.Animal.getDefaultInstance() : animalRef_;
      }
    }
    /**
     * <code>.Animal animalRef = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        via.sdj3.slaughterhousegrpcspringboot.protobuf.Animal, via.sdj3.slaughterhousegrpcspringboot.protobuf.Animal.Builder, via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalOrBuilder> 
        getAnimalRefFieldBuilder() {
      if (animalRefBuilder_ == null) {
        animalRefBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            via.sdj3.slaughterhousegrpcspringboot.protobuf.Animal, via.sdj3.slaughterhousegrpcspringboot.protobuf.Animal.Builder, via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalOrBuilder>(
                getAnimalRef(),
                getParentForChildren(),
                isClean());
        animalRef_ = null;
      }
      return animalRefBuilder_;
    }

    private java.lang.Object type_ = "";
    /**
     * <code>string type = 4;</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type = 4;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type = 4;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = getDefaultInstance().getType();
      onChanged();
      return this;
    }
    /**
     * <code>string type = 4;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      type_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AnimalPart)
  }

  // @@protoc_insertion_point(class_scope:AnimalPart)
  private static final via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart();
  }

  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AnimalPart>
      PARSER = new com.google.protobuf.AbstractParser<AnimalPart>() {
    @java.lang.Override
    public AnimalPart parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AnimalPart(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AnimalPart> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AnimalPart> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

