// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Slaughterhouse.proto

package via.sdj3.slaughterhousegrpcspringboot.protobuf;

public interface AnimalOriginOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AnimalOrigin)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string origin = 1;</code>
   * @return The origin.
   */
  java.lang.String getOrigin();
  /**
   * <code>string origin = 1;</code>
   * @return The bytes for origin.
   */
  com.google.protobuf.ByteString
      getOriginBytes();
}
