// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Slaughterhouse.proto

package via.sdj3.slaughterhousegrpcspringboot.protobuf;

public interface AnimalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Animal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double weight = 1;</code>
   * @return The weight.
   */
  double getWeight();

  /**
   * <code>int32 animalNr = 2;</code>
   * @return The animalNr.
   */
  int getAnimalNr();

  /**
   * <code>string type = 3;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 3;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string origin = 4;</code>
   * @return The origin.
   */
  java.lang.String getOrigin();
  /**
   * <code>string origin = 4;</code>
   * @return The bytes for origin.
   */
  com.google.protobuf.ByteString
      getOriginBytes();
}
