// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Slaughterhouse.proto

package via.sdj3.slaughterhousegrpcspringboot.protobuf;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Empty)
    com.google.protobuf.MessageOrBuilder {
}
