// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Slaughterhouse.proto

package via.sdj3.slaughterhousegrpcspringboot.protobuf;

/**
 * Protobuf type {@code ProductPacks}
 */
public final class ProductPacks extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ProductPacks)
    ProductPacksOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProductPacks.newBuilder() to construct.
  private ProductPacks(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProductPacks() {
    trayRef_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProductPacks();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProductPacks(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            packNr_ = input.readInt32();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              trayRef_ = new java.util.ArrayList<via.sdj3.slaughterhousegrpcspringboot.protobuf.Trays>();
              mutable_bitField0_ |= 0x00000001;
            }
            trayRef_.add(
                input.readMessage(via.sdj3.slaughterhousegrpcspringboot.protobuf.Trays.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        trayRef_ = java.util.Collections.unmodifiableList(trayRef_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sdj3.slaughterhousegrpcspringboot.protobuf.SlaughterhouseOuterClass.internal_static_ProductPacks_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sdj3.slaughterhousegrpcspringboot.protobuf.SlaughterhouseOuterClass.internal_static_ProductPacks_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks.class, via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks.Builder.class);
  }

  public static final int PACKNR_FIELD_NUMBER = 1;
  private int packNr_;
  /**
   * <code>int32 packNr = 1;</code>
   * @return The packNr.
   */
  @java.lang.Override
  public int getPackNr() {
    return packNr_;
  }

  public static final int TRAYREF_FIELD_NUMBER = 2;
  private java.util.List<via.sdj3.slaughterhousegrpcspringboot.protobuf.Trays> trayRef_;
  /**
   * <code>repeated .Trays trayRef = 2;</code>
   */
  @java.lang.Override
  public java.util.List<via.sdj3.slaughterhousegrpcspringboot.protobuf.Trays> getTrayRefList() {
    return trayRef_;
  }
  /**
   * <code>repeated .Trays trayRef = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends via.sdj3.slaughterhousegrpcspringboot.protobuf.TraysOrBuilder> 
      getTrayRefOrBuilderList() {
    return trayRef_;
  }
  /**
   * <code>repeated .Trays trayRef = 2;</code>
   */
  @java.lang.Override
  public int getTrayRefCount() {
    return trayRef_.size();
  }
  /**
   * <code>repeated .Trays trayRef = 2;</code>
   */
  @java.lang.Override
  public via.sdj3.slaughterhousegrpcspringboot.protobuf.Trays getTrayRef(int index) {
    return trayRef_.get(index);
  }
  /**
   * <code>repeated .Trays trayRef = 2;</code>
   */
  @java.lang.Override
  public via.sdj3.slaughterhousegrpcspringboot.protobuf.TraysOrBuilder getTrayRefOrBuilder(
      int index) {
    return trayRef_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (packNr_ != 0) {
      output.writeInt32(1, packNr_);
    }
    for (int i = 0; i < trayRef_.size(); i++) {
      output.writeMessage(2, trayRef_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (packNr_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, packNr_);
    }
    for (int i = 0; i < trayRef_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, trayRef_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks)) {
      return super.equals(obj);
    }
    via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks other = (via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks) obj;

    if (getPackNr()
        != other.getPackNr()) return false;
    if (!getTrayRefList()
        .equals(other.getTrayRefList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PACKNR_FIELD_NUMBER;
    hash = (53 * hash) + getPackNr();
    if (getTrayRefCount() > 0) {
      hash = (37 * hash) + TRAYREF_FIELD_NUMBER;
      hash = (53 * hash) + getTrayRefList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ProductPacks}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ProductPacks)
      via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sdj3.slaughterhousegrpcspringboot.protobuf.SlaughterhouseOuterClass.internal_static_ProductPacks_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sdj3.slaughterhousegrpcspringboot.protobuf.SlaughterhouseOuterClass.internal_static_ProductPacks_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks.class, via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks.Builder.class);
    }

    // Construct using via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTrayRefFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      packNr_ = 0;

      if (trayRefBuilder_ == null) {
        trayRef_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        trayRefBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sdj3.slaughterhousegrpcspringboot.protobuf.SlaughterhouseOuterClass.internal_static_ProductPacks_descriptor;
    }

    @java.lang.Override
    public via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks getDefaultInstanceForType() {
      return via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks.getDefaultInstance();
    }

    @java.lang.Override
    public via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks build() {
      via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks buildPartial() {
      via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks result = new via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks(this);
      int from_bitField0_ = bitField0_;
      result.packNr_ = packNr_;
      if (trayRefBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          trayRef_ = java.util.Collections.unmodifiableList(trayRef_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.trayRef_ = trayRef_;
      } else {
        result.trayRef_ = trayRefBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks) {
        return mergeFrom((via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks other) {
      if (other == via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks.getDefaultInstance()) return this;
      if (other.getPackNr() != 0) {
        setPackNr(other.getPackNr());
      }
      if (trayRefBuilder_ == null) {
        if (!other.trayRef_.isEmpty()) {
          if (trayRef_.isEmpty()) {
            trayRef_ = other.trayRef_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTrayRefIsMutable();
            trayRef_.addAll(other.trayRef_);
          }
          onChanged();
        }
      } else {
        if (!other.trayRef_.isEmpty()) {
          if (trayRefBuilder_.isEmpty()) {
            trayRefBuilder_.dispose();
            trayRefBuilder_ = null;
            trayRef_ = other.trayRef_;
            bitField0_ = (bitField0_ & ~0x00000001);
            trayRefBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTrayRefFieldBuilder() : null;
          } else {
            trayRefBuilder_.addAllMessages(other.trayRef_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int packNr_ ;
    /**
     * <code>int32 packNr = 1;</code>
     * @return The packNr.
     */
    @java.lang.Override
    public int getPackNr() {
      return packNr_;
    }
    /**
     * <code>int32 packNr = 1;</code>
     * @param value The packNr to set.
     * @return This builder for chaining.
     */
    public Builder setPackNr(int value) {
      
      packNr_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 packNr = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPackNr() {
      
      packNr_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<via.sdj3.slaughterhousegrpcspringboot.protobuf.Trays> trayRef_ =
      java.util.Collections.emptyList();
    private void ensureTrayRefIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        trayRef_ = new java.util.ArrayList<via.sdj3.slaughterhousegrpcspringboot.protobuf.Trays>(trayRef_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sdj3.slaughterhousegrpcspringboot.protobuf.Trays, via.sdj3.slaughterhousegrpcspringboot.protobuf.Trays.Builder, via.sdj3.slaughterhousegrpcspringboot.protobuf.TraysOrBuilder> trayRefBuilder_;

    /**
     * <code>repeated .Trays trayRef = 2;</code>
     */
    public java.util.List<via.sdj3.slaughterhousegrpcspringboot.protobuf.Trays> getTrayRefList() {
      if (trayRefBuilder_ == null) {
        return java.util.Collections.unmodifiableList(trayRef_);
      } else {
        return trayRefBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Trays trayRef = 2;</code>
     */
    public int getTrayRefCount() {
      if (trayRefBuilder_ == null) {
        return trayRef_.size();
      } else {
        return trayRefBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Trays trayRef = 2;</code>
     */
    public via.sdj3.slaughterhousegrpcspringboot.protobuf.Trays getTrayRef(int index) {
      if (trayRefBuilder_ == null) {
        return trayRef_.get(index);
      } else {
        return trayRefBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Trays trayRef = 2;</code>
     */
    public Builder setTrayRef(
        int index, via.sdj3.slaughterhousegrpcspringboot.protobuf.Trays value) {
      if (trayRefBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTrayRefIsMutable();
        trayRef_.set(index, value);
        onChanged();
      } else {
        trayRefBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Trays trayRef = 2;</code>
     */
    public Builder setTrayRef(
        int index, via.sdj3.slaughterhousegrpcspringboot.protobuf.Trays.Builder builderForValue) {
      if (trayRefBuilder_ == null) {
        ensureTrayRefIsMutable();
        trayRef_.set(index, builderForValue.build());
        onChanged();
      } else {
        trayRefBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Trays trayRef = 2;</code>
     */
    public Builder addTrayRef(via.sdj3.slaughterhousegrpcspringboot.protobuf.Trays value) {
      if (trayRefBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTrayRefIsMutable();
        trayRef_.add(value);
        onChanged();
      } else {
        trayRefBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Trays trayRef = 2;</code>
     */
    public Builder addTrayRef(
        int index, via.sdj3.slaughterhousegrpcspringboot.protobuf.Trays value) {
      if (trayRefBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTrayRefIsMutable();
        trayRef_.add(index, value);
        onChanged();
      } else {
        trayRefBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Trays trayRef = 2;</code>
     */
    public Builder addTrayRef(
        via.sdj3.slaughterhousegrpcspringboot.protobuf.Trays.Builder builderForValue) {
      if (trayRefBuilder_ == null) {
        ensureTrayRefIsMutable();
        trayRef_.add(builderForValue.build());
        onChanged();
      } else {
        trayRefBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Trays trayRef = 2;</code>
     */
    public Builder addTrayRef(
        int index, via.sdj3.slaughterhousegrpcspringboot.protobuf.Trays.Builder builderForValue) {
      if (trayRefBuilder_ == null) {
        ensureTrayRefIsMutable();
        trayRef_.add(index, builderForValue.build());
        onChanged();
      } else {
        trayRefBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Trays trayRef = 2;</code>
     */
    public Builder addAllTrayRef(
        java.lang.Iterable<? extends via.sdj3.slaughterhousegrpcspringboot.protobuf.Trays> values) {
      if (trayRefBuilder_ == null) {
        ensureTrayRefIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, trayRef_);
        onChanged();
      } else {
        trayRefBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Trays trayRef = 2;</code>
     */
    public Builder clearTrayRef() {
      if (trayRefBuilder_ == null) {
        trayRef_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        trayRefBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Trays trayRef = 2;</code>
     */
    public Builder removeTrayRef(int index) {
      if (trayRefBuilder_ == null) {
        ensureTrayRefIsMutable();
        trayRef_.remove(index);
        onChanged();
      } else {
        trayRefBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Trays trayRef = 2;</code>
     */
    public via.sdj3.slaughterhousegrpcspringboot.protobuf.Trays.Builder getTrayRefBuilder(
        int index) {
      return getTrayRefFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Trays trayRef = 2;</code>
     */
    public via.sdj3.slaughterhousegrpcspringboot.protobuf.TraysOrBuilder getTrayRefOrBuilder(
        int index) {
      if (trayRefBuilder_ == null) {
        return trayRef_.get(index);  } else {
        return trayRefBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Trays trayRef = 2;</code>
     */
    public java.util.List<? extends via.sdj3.slaughterhousegrpcspringboot.protobuf.TraysOrBuilder> 
         getTrayRefOrBuilderList() {
      if (trayRefBuilder_ != null) {
        return trayRefBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(trayRef_);
      }
    }
    /**
     * <code>repeated .Trays trayRef = 2;</code>
     */
    public via.sdj3.slaughterhousegrpcspringboot.protobuf.Trays.Builder addTrayRefBuilder() {
      return getTrayRefFieldBuilder().addBuilder(
          via.sdj3.slaughterhousegrpcspringboot.protobuf.Trays.getDefaultInstance());
    }
    /**
     * <code>repeated .Trays trayRef = 2;</code>
     */
    public via.sdj3.slaughterhousegrpcspringboot.protobuf.Trays.Builder addTrayRefBuilder(
        int index) {
      return getTrayRefFieldBuilder().addBuilder(
          index, via.sdj3.slaughterhousegrpcspringboot.protobuf.Trays.getDefaultInstance());
    }
    /**
     * <code>repeated .Trays trayRef = 2;</code>
     */
    public java.util.List<via.sdj3.slaughterhousegrpcspringboot.protobuf.Trays.Builder> 
         getTrayRefBuilderList() {
      return getTrayRefFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sdj3.slaughterhousegrpcspringboot.protobuf.Trays, via.sdj3.slaughterhousegrpcspringboot.protobuf.Trays.Builder, via.sdj3.slaughterhousegrpcspringboot.protobuf.TraysOrBuilder> 
        getTrayRefFieldBuilder() {
      if (trayRefBuilder_ == null) {
        trayRefBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            via.sdj3.slaughterhousegrpcspringboot.protobuf.Trays, via.sdj3.slaughterhousegrpcspringboot.protobuf.Trays.Builder, via.sdj3.slaughterhousegrpcspringboot.protobuf.TraysOrBuilder>(
                trayRef_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        trayRef_ = null;
      }
      return trayRefBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ProductPacks)
  }

  // @@protoc_insertion_point(class_scope:ProductPacks)
  private static final via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks();
  }

  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProductPacks>
      PARSER = new com.google.protobuf.AbstractParser<ProductPacks>() {
    @java.lang.Override
    public ProductPacks parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProductPacks(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProductPacks> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProductPacks> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacks getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

