// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Slaughterhouse.proto

package via.sdj3.slaughterhousegrpcspringboot.protobuf;

public interface AnimalOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Animal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double weight = 1;</code>
   * @return The weight.
   */
  double getWeight();

  /**
   * <code>int32 animalNr = 2;</code>
   * @return The animalNr.
   */
  int getAnimalNr();
}
