// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Slaughterhouse.proto

package via.sdj3.slaughterhousegrpcspringboot.protobuf;

/**
 * Protobuf type {@code ProductPacksResponse}
 */
public final class ProductPacksResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ProductPacksResponse)
    ProductPacksResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProductPacksResponse.newBuilder() to construct.
  private ProductPacksResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProductPacksResponse() {
    productPackId_ = emptyIntList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProductPacksResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProductPacksResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              productPackId_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            productPackId_.addInt(input.readInt32());
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              productPackId_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              productPackId_.addInt(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        productPackId_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sdj3.slaughterhousegrpcspringboot.protobuf.SlaughterhouseOuterClass.internal_static_ProductPacksResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sdj3.slaughterhousegrpcspringboot.protobuf.SlaughterhouseOuterClass.internal_static_ProductPacksResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse.class, via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse.Builder.class);
  }

  public static final int PRODUCTPACKID_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.IntList productPackId_;
  /**
   * <code>repeated int32 productPackId = 1;</code>
   * @return A list containing the productPackId.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getProductPackIdList() {
    return productPackId_;
  }
  /**
   * <code>repeated int32 productPackId = 1;</code>
   * @return The count of productPackId.
   */
  public int getProductPackIdCount() {
    return productPackId_.size();
  }
  /**
   * <code>repeated int32 productPackId = 1;</code>
   * @param index The index of the element to return.
   * @return The productPackId at the given index.
   */
  public int getProductPackId(int index) {
    return productPackId_.getInt(index);
  }
  private int productPackIdMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getProductPackIdList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(productPackIdMemoizedSerializedSize);
    }
    for (int i = 0; i < productPackId_.size(); i++) {
      output.writeInt32NoTag(productPackId_.getInt(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < productPackId_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(productPackId_.getInt(i));
      }
      size += dataSize;
      if (!getProductPackIdList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      productPackIdMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse)) {
      return super.equals(obj);
    }
    via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse other = (via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse) obj;

    if (!getProductPackIdList()
        .equals(other.getProductPackIdList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getProductPackIdCount() > 0) {
      hash = (37 * hash) + PRODUCTPACKID_FIELD_NUMBER;
      hash = (53 * hash) + getProductPackIdList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ProductPacksResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ProductPacksResponse)
      via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sdj3.slaughterhousegrpcspringboot.protobuf.SlaughterhouseOuterClass.internal_static_ProductPacksResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sdj3.slaughterhousegrpcspringboot.protobuf.SlaughterhouseOuterClass.internal_static_ProductPacksResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse.class, via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse.Builder.class);
    }

    // Construct using via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      productPackId_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sdj3.slaughterhousegrpcspringboot.protobuf.SlaughterhouseOuterClass.internal_static_ProductPacksResponse_descriptor;
    }

    @java.lang.Override
    public via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse getDefaultInstanceForType() {
      return via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse.getDefaultInstance();
    }

    @java.lang.Override
    public via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse build() {
      via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse buildPartial() {
      via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse result = new via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        productPackId_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.productPackId_ = productPackId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse) {
        return mergeFrom((via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse other) {
      if (other == via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse.getDefaultInstance()) return this;
      if (!other.productPackId_.isEmpty()) {
        if (productPackId_.isEmpty()) {
          productPackId_ = other.productPackId_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureProductPackIdIsMutable();
          productPackId_.addAll(other.productPackId_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.IntList productPackId_ = emptyIntList();
    private void ensureProductPackIdIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        productPackId_ = mutableCopy(productPackId_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int32 productPackId = 1;</code>
     * @return A list containing the productPackId.
     */
    public java.util.List<java.lang.Integer>
        getProductPackIdList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(productPackId_) : productPackId_;
    }
    /**
     * <code>repeated int32 productPackId = 1;</code>
     * @return The count of productPackId.
     */
    public int getProductPackIdCount() {
      return productPackId_.size();
    }
    /**
     * <code>repeated int32 productPackId = 1;</code>
     * @param index The index of the element to return.
     * @return The productPackId at the given index.
     */
    public int getProductPackId(int index) {
      return productPackId_.getInt(index);
    }
    /**
     * <code>repeated int32 productPackId = 1;</code>
     * @param index The index to set the value at.
     * @param value The productPackId to set.
     * @return This builder for chaining.
     */
    public Builder setProductPackId(
        int index, int value) {
      ensureProductPackIdIsMutable();
      productPackId_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 productPackId = 1;</code>
     * @param value The productPackId to add.
     * @return This builder for chaining.
     */
    public Builder addProductPackId(int value) {
      ensureProductPackIdIsMutable();
      productPackId_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 productPackId = 1;</code>
     * @param values The productPackId to add.
     * @return This builder for chaining.
     */
    public Builder addAllProductPackId(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureProductPackIdIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, productPackId_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 productPackId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductPackId() {
      productPackId_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ProductPacksResponse)
  }

  // @@protoc_insertion_point(class_scope:ProductPacksResponse)
  private static final via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse();
  }

  public static via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProductPacksResponse>
      PARSER = new com.google.protobuf.AbstractParser<ProductPacksResponse>() {
    @java.lang.Override
    public ProductPacksResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProductPacksResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProductPacksResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProductPacksResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sdj3.slaughterhousegrpcspringboot.protobuf.ProductPacksResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

