// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Slaughterhouse.proto

package via.sdj3.slaughterhousegrpcspringboot.protobuf;

public interface ProductPacksResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductPacksResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 productPackId = 1;</code>
   * @return A list containing the productPackId.
   */
  java.util.List<java.lang.Integer> getProductPackIdList();
  /**
   * <code>repeated int32 productPackId = 1;</code>
   * @return The count of productPackId.
   */
  int getProductPackIdCount();
  /**
   * <code>repeated int32 productPackId = 1;</code>
   * @param index The index of the element to return.
   * @return The productPackId at the given index.
   */
  int getProductPackId(int index);
}
