// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Slaughterhouse.proto

package via.sdj3.slaughterhousegrpcspringboot.protobuf;

public interface TraysOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Trays)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .AnimalPart partType = 1;</code>
   */
  java.util.List<via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart> 
      getPartTypeList();
  /**
   * <code>repeated .AnimalPart partType = 1;</code>
   */
  via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPart getPartType(int index);
  /**
   * <code>repeated .AnimalPart partType = 1;</code>
   */
  int getPartTypeCount();
  /**
   * <code>repeated .AnimalPart partType = 1;</code>
   */
  java.util.List<? extends via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPartOrBuilder> 
      getPartTypeOrBuilderList();
  /**
   * <code>repeated .AnimalPart partType = 1;</code>
   */
  via.sdj3.slaughterhousegrpcspringboot.protobuf.AnimalPartOrBuilder getPartTypeOrBuilder(
      int index);

  /**
   * <code>double maximumWeight = 2;</code>
   * @return The maximumWeight.
   */
  double getMaximumWeight();

  /**
   * <code>int32 trayNr = 3;</code>
   * @return The trayNr.
   */
  int getTrayNr();
}
