// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Slaughterhouse.proto

package via.sdj3.slaughterhouseapi.protobuf;

public interface AnimalsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Animals)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Animal animals = 1;</code>
   */
  java.util.List<via.sdj3.slaughterhouseapi.protobuf.Animal> 
      getAnimalsList();
  /**
   * <code>repeated .Animal animals = 1;</code>
   */
  via.sdj3.slaughterhouseapi.protobuf.Animal getAnimals(int index);
  /**
   * <code>repeated .Animal animals = 1;</code>
   */
  int getAnimalsCount();
  /**
   * <code>repeated .Animal animals = 1;</code>
   */
  java.util.List<? extends via.sdj3.slaughterhouseapi.protobuf.AnimalOrBuilder> 
      getAnimalsOrBuilderList();
  /**
   * <code>repeated .Animal animals = 1;</code>
   */
  via.sdj3.slaughterhouseapi.protobuf.AnimalOrBuilder getAnimalsOrBuilder(
      int index);
}
