// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Slaughterhouse.proto

package via.sdj3.slaughterhouseapi.protobuf;

public interface ProductPacksOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductPacks)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 packNr = 1;</code>
   * @return The packNr.
   */
  int getPackNr();

  /**
   * <code>repeated .Trays trayRef = 2;</code>
   */
  java.util.List<via.sdj3.slaughterhouseapi.protobuf.Trays> 
      getTrayRefList();
  /**
   * <code>repeated .Trays trayRef = 2;</code>
   */
  via.sdj3.slaughterhouseapi.protobuf.Trays getTrayRef(int index);
  /**
   * <code>repeated .Trays trayRef = 2;</code>
   */
  int getTrayRefCount();
  /**
   * <code>repeated .Trays trayRef = 2;</code>
   */
  java.util.List<? extends via.sdj3.slaughterhouseapi.protobuf.TraysOrBuilder> 
      getTrayRefOrBuilderList();
  /**
   * <code>repeated .Trays trayRef = 2;</code>
   */
  via.sdj3.slaughterhouseapi.protobuf.TraysOrBuilder getTrayRefOrBuilder(
      int index);
}
